### ISSUE TITLE
problems with corporative o365

### ISSUE THREAD

**Issue by X-n3t** [sensepost/ruler#124]
![imagen](https://user-images.githubusercontent.com/52056830/96739325-f7ae2b00-13bf-11eb-8c0d-1ca2aae9b06b.png)

**Comment by derazo1** [comment]
any solution for this?

**Comment by staaldraad** [comment]
@X-n3t @derazo1 have you tried without `--o365`? This is just a [short-cut to try autodiscover](https://github.com/sensepost/ruler/wiki#office365) directly against O365 instead of going through the usual path of company --> O365.

Also try with the `--basic` flag to force basic auth. This might also require the `--domain` flag.
