### ISSUE TITLE
RULER NOT WORKING 

### ISSUE THREAD

**Issue by xxxvintage** [sensepost/ruler#141]
Ruler not finding Autodiscover URL when I try to check if any existing rule.

![image](https://github.com/sensepost/ruler/assets/93237147/760d4e6e-6003-4954-8131-d1784c802a04)

**Comment by staaldraad** [comment]
Autodiscover is best effort and might not always work, since the autodiscover service may not have been correctly configured. The timeout here suggests that the discovered domain from step 2 does not have a reachable IP address or the exchange service is not listening for external connections.
 This can be worked around by using `--url` with the correct URL to the exchange service, if the exchange server is publicly accessible.
