### ISSUE TITLE
Getting failed attempt with "brute" but not with "display"

### ISSUE THREAD

**Issue by flacostec** [sensepost/ruler#33]
For a reason that I don't understand, I'm getting a "failed attempt" when I am using a set of credentials that works with the following command: 
> ruler --o365 --domain mydomain.com brute --users email.txt --passwords passwd.txt -v

However if I do : 
> ruler --o365 --domain mydomain.com --email me@mydomain.com --password mypassword display

It returns me all my rules. I tried different combination in email.txt (full email, etc.) but it gives the same result. I also tried --basic and --userpass combination.

Any idea why ?

**Comment by staaldraad** [comment]
Thanks for the report. I will need to look into this, setting ```--basic``` should do the trick for Office365 domains. 

I'll do some tests and see what's going on. Thanks again for letting me know!

**Comment by staaldraad** [comment]
Ah ok. Simple fix :+1: 

It's specifically to do with Office365 - The autodiscover does a cross-domain redirect, which Go treats as insecure and doesn't forward the BasicAuth credentials to the redirect (this is correct behaviour). I had built in a work-around for autodiscover, but forgot to add this to the ```brute``` command.

```
[*] Autodiscover step 2 - URL: http://autodiscover.0x04.cc/autodiscover/autodiscover.xml
[*] Request for http://autodiscover.0x04.cc/autodiscover/autodiscover.xml redirected. Following to https://autodiscover-s.outlook.com/autodiscover/autodiscover.xml
```

I've added the fix to brute, so it should work now. I've updated the Ruler binaries to match (same Release: [2.1.4](https://github.com/sensepost/ruler/releases/tag/2.1.4)). Thanks for the report.

Fixed with: https://github.com/sensepost/ruler/commit/65926cd0964056c6c734ac4f63f658e99ecb1a94
