### ISSUE TITLE
Option to set RPC URL

### ISSUE THREAD

**Issue by leoloobeek** [sensepost/ruler#37]
Ran into an issue where the RPC URL set from Autodiscover was a separate system that had been decommissioned. By editing the /etc/hosts file I was able to get around it, just thought I'd suggest including a command line option to manually set the RPC URL. I'd submit a PR but I'm no Gopher.

Looks like where this is set is here: https://github.com/sensepost/ruler/blob/152d9a433c98730c2e1557d88111d076077813dc/autodiscover/autodiscover.go#L118

Just a suggestion, might be a one off. Appreciate the hard work!

**Comment by staaldraad** [comment]
Hi!

Thanks for the suggestion. Actually had the same situation arise a few times recently. What I've attempted is to move some of this into a _config_ file, rather than supplying it all through the cmdline. One of these options you can specify in the config is _rpcurl_ - I think this is exactly what you might be looking for :+1: 

https://github.com/sensepost/ruler/wiki/Getting-Started#the-config-file

It's a pretty new addition, I added it last week if memory serves, so if you try it out and there are improvements you can see, please let me know!

**Comment by leoloobeek** [comment]
Awesome, I remember seeing the config option but didn't think anything of it. Thank!
