### ISSUE TITLE
Getting RPC Timeout with Ruler

### ISSUE THREAD

**Issue by lsuto** [sensepost/ruler#51]
I am to find the RPC endpoint and start setting up channels, but then I get this error: 
[*] Setting up channels
[+] Binding to RPC
ERROR: 2017/08/29 15:49:56 RPC Timeout
ERROR: 2017/08/29 15:49:56 mapi: a transport layer error occurred. An error occurred setting up RPC. Invalid HTTP response: [HTTP/1.1 503 RPC Error: c0021009]

**Comment by staaldraad** [comment]
Hi!

The HTTP 503 error is being returned by IIS and indicates _service unavailable_. There are multiple possible reasons for this. From what I can find it can be 64-bit IIS trying to load 32-bit rpcproxy.dll or an issue with the SSL certificate on the backend server. 

What you can try; 
1) use the config file to try and force MAPI/HTTP (https://github.com/sensepost/ruler/wiki/Getting-Started#the-config-file) - you'll want to set ```rpc: false ```
2) Use the MSFT connectivity analyser to determine if the issue is with the IIS server or Ruler's way of connecting to Exchange. This can be done here: https://testconnectivity.microsoft.com/ (using Outlook connectivity) or in Outlook.

Hope that helps!
