### ISSUE TITLE
Proxy is not used all times

### ISSUE THREAD

**Issue by 0xb35c** [sensepost/ruler#52]
Hi,

when adding a proxy with the --proxy flag it isn't used all times. Here is my call:

`ruler-linux64 --verbose --proxy https://127.0.0.1:8080 -e target@some.domain -d some.domain -k u`

The request to `https://some.domain/autodiscover/autodiscover.xml` does not pass my proxy, but the second one to `https://autodiscover.some.domain/autodiscover/autodiscover.xml` does. (According to both Burp and Wireshark)

The expected behavior would be, that the set proxy is used for all requests. 

[edit]
Interesting: If I prepend the cli call with https_proxy I get a segfault:
```
[+] Checking if domain is hosted on Office 365
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x4016e6]

goroutine 1 [running]:
panic(0x777400, 0xc4200120d0)
	/usr/lib/golang/src/runtime/panic.go:500 +0x1a1
main.discover(0xc42008a780, 0x4, 0xc4200644e0)
	/home/staaldraad/Go/gopath/src/github.com/sensepost/ruler/ruler.go:77 +0x596
main.main.func7(0xc42008a780, 0x0, 0xc42008a780)
	/home/staaldraad/Go/gopath/src/github.com/sensepost/ruler/ruler.go:985 +0x2f
github.com/urfave/cli.HandleAction(0x765a60, 0x807748, 0xc42008a780, 0xc420064400, 0x0)
	/home/staaldraad/Go/gopath/src/github.com/urfave/cli/app.go:483 +0xb9
github.com/urfave/cli.Command.Run(0x7d5f64, 0xc, 0x0, 0x0, 0xc4200135b0, 0x1, 0x1, 0x7e7cee, 0x42, 0x0, ...)
	/home/staaldraad/Go/gopath/src/github.com/urfave/cli/command.go:193 +0xb96
github.com/urfave/cli.(*App).Run(0xc420084b60, 0xc42000c0c0, 0xc, 0xc, 0x0, 0x0)
	/home/staaldraad/Go/gopath/src/github.com/urfave/cli/app.go:250 +0x812
main.main()
	/home/staaldraad/Go/gopath/src/github.com/sensepost/ruler/ruler.go:1240 +0x2cd0
```

**Comment by staaldraad** [comment]
Hi!

Thanks for the report.

To be honest the proxy option has not been heavily tested. In theory all requests should be going through as they are using the same transport. I will have to investigate why this isn't working case. This was added because the environment proxy seemed to be getting ignored, seems I missed something in the implementation. 

I'll add this to the TODO list, unfortunately it will have to take a backseat until after the big release end of this month. But maybe I'll be able to sneak it in with the update as well!

**Comment by 0xb35c** [comment]
Yeah, I took a look into to the code and I had the same impression regarding the transport.
But I'm not (yet?) very familiar with Go, so I was not able to find the cause.

**Comment by staaldraad** [comment]
I think I know where I missed the proxy config :+1: 

in ```$GOPATH/src/github.com/sensepost/ruler/autodiscover/autodiscover.xml``` line 258, there should be an additional argument. Namely **Proxy: SessionConfig.Proxy**

https://github.com/sensepost/ruler/blob/master/autodiscover/autodiscover.go#L258

With that added, it will look like this:
```
client = http.Client{
			Transport: &httpntlm.NtlmTransport{
				Domain:    SessionConfig.Domain,
				User:      SessionConfig.User,
				Password:  SessionConfig.Pass,
				NTHash:    SessionConfig.NTHash,
				Insecure:  SessionConfig.Insecure,
				CookieJar: SessionConfig.CookieJar,
				Proxy:     SessionConfig.Proxy,
			},
			Jar: SessionConfig.CookieJar,
		}
```

This should ensure that requests using the httpNTLM Transport are also sent to the proxy. 
You will need NTLM platform auth setup in burp. For any MAPI/HTTP requests you'll want to have it set to show **other binary** .

RPC/HTTP will not work over the proxy - guaranteed - as I'm creating TCP socket connections for those and creating my own HTTP request for RPC_DATA_IN and RPC_DATA_OUT (and i'm not going to add proxy support to these)

If you are proxying to see the content, then I can recommend the setup I use for RPC/HTTP.
I use https://github.com/staaldraad/tcpprox and set it up as follows:

1.) change /etc/hosts so that the RPC/HTTP domain points to 127.0.0.1
2.) use: ```./tcpprox -s -l 127.0.0.1 -p 443 -r x.x.x.x:443```

Where *x.x.x.x* is the IP address of the RPC/HTTP domain. In all likelihood it will require HTTPS and thus the use of the ```-s```

**Comment by 0xb35c** [comment]
Yep, that seems to fix it as far as i can see.
Thank you.

Also I'd suggest to add the stuff with the RCP/HTTP proxying to the Readme or so to document that. ;-)

Should I keep the issue open as reminder?

**Comment by staaldraad** [comment]
Awesome :+1:  

I've added it into the new branch and should be live with the other fixes. 

Thanks so much for letting me know!

I'll update the wiki with the proxy and rpc/http details. It reminds me that there is a big wiki update needed as well :(

happy for you to close this :+1:
