### ISSUE TITLE
Retrieve Rules - Panic on parsing response

### ISSUE THREAD

**Issue by LFBernardo** [sensepost/ruler#57]
Not sure if this is because of Bash for Windows (WSL) but receive the following output. Will test from Kali as well on the specific mailbox

![image](https://user-images.githubusercontent.com/18407412/31441991-3e74bda8-ae95-11e7-9010-2af7307d14d3.png)

**Comment by staaldraad** [comment]
Hi! 

This seems to be the latest version (2.1.9 - released today), correct?

Is this via RPC/HTTP or MAPI/HTTP? 
If it's RPC/HTTP, I think there might be too many rows/data being sent, and Ruler ends up with a smaller than expected response (counter intuitive right? but the RPC doesn't send the bigger packets and we end up missing part of the data)

Having a look at the code now to see if I've changed something to break this. 

If you are using 2.1.9, could you try with an older version, such as 2.1.7 and see if the panic also occurs?

thanks!

**Comment by staaldraad** [comment]
Ok, looks like it's in the new code. I added functionality to the rules to try and display the rule action. Crashing out on that for an odd reason. 

Going to test a quick fix and push if it works. Would be appreciative if you could test it out

**Comment by LFBernardo** [comment]
Will do

**Comment by LFBernardo** [comment]
Doesn't complete externally (not same issue). Will have to test internally in the morning. Will keep you posted.


![image](https://user-images.githubusercontent.com/18407412/31449669-d71f9354-aea7-11e7-9d0d-0ca8b8a986d5.png)

**Comment by LFBernardo** [comment]
Got it to run with -b  starts bombing out after line 7 of output. Will mail you output.

**Comment by RedSec-Shay** [comment]
getting panic as well for both RPC and MAPI :

	
![image](https://user-images.githubusercontent.com/8040198/32023080-4204d324-b9a6-11e7-9515-f7593724d25d.png)

**Comment by staaldraad** [comment]
Hi @RedSec-Shay 

This seems to be a different issue. The actual panic is occurring in the *net/http* library rather than Ruler code.

The crash is when you are brute-forcing correct? It seems like there is a redirect from the server which causes the nil pointer. My guess is that there is a 301/302 redirect but the location header is empty.

**Comment by RedSec-Shay** [comment]
Thanks @staaldraad . 
the strange thing is that it works fine for first ~10 or more requests , before the Panic happen . 
moreover , it is working with a single user (with known pass) .  Wouldn't a missing location header fail on every single request ?
Any suggestion ? (could I maybe follow the redirect manually and feed the destination url to ruler ? )

**Comment by staaldraad** [comment]
The bruteforce gets into weird mutex issues at times due to the concurrency. Thought this was fixed in the latest version.

If you are on the latest version, you can try lower the "thread" count with ```--threads 1```
It will be much slower but you won't see that issue anymore. A friend also said leaving out --verbose prevents the error from occurring (no idea why)

**Comment by RedSec-Shay** [comment]
Can confirm setting Threads to 1 seems to work.
Thanks again for the your help.
