### ISSUE TITLE
New Homepage Exploit

### ISSUE THREAD

**Issue by SecureThisShit** [sensepost/ruler#58]
Hi,

i tried the Homepage Exploit today, but it didnt work here. It was possible to get a Html Only Homepage, but all the ActiveX Wscript.Shell Parts ended in an error page.
The Error Page stated: Site cannot be displayed, make sure that the web-Adress ieframe.dll/dnserrordiagoff.html# is correct.

No Notepad gets executed. The Patch is not applied.

I tried to include the Notepad POC Page manually without Ruler:

<html>
<head>
<meta http-equiv="Content-Language" content="en-us">
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<title>Outlook</title>
<script id=clientEventHandlersVBS language=vbscript>

</script>
</head>
<body>
 <object classid="clsid:0006F063-0000-0000-C000-000000000046" id="ViewCtl1" data="" width="100%" height="100%"></object>
</body>
</html>

Some Ideas how to get this working?

Greetings

**Comment by staaldraad** [comment]
Hi!

That error message gets displayed when the ieframe is unable to load the page. It’s likely that the page was unreachable when the home page was set. Outlook also caches the homepage, so if it failed initially it might not bother to try and reload the page. The best in this case is to unset and reset the home page.

I would double check that the URL is correct and reachable. If the activex fails, you’ll usually be left with a blank white page, rather than the built in ieframe error pages.

Hope that helps!

I think I included a URL to a gist hosting the notepad PoC in the Ruler Wiki. You could try that as well :)

**Comment by SecureThisShit** [comment]
Thanks for your reply,
the POC worked correctly. But i had to allow active X in a Pop-Up from Outlook.

**Comment by staaldraad** [comment]
Thanks for the update! Interesting that there was an ActiveX pop-up, I wonder if the system had a stricter internet security policy set.

My tests were done on a standard install of Windows 10 with no changes to the internet security zones. If you have some additional information about your configuration, I would appreciate it :)

**Comment by SecureThisShit** [comment]
I also used a Windows 10 Client, IE Security Settings for Internet Connections are set to "Middle to High" / No Download of unsigned Active-X elements ( I think. Secured Mode is activated.
Advanced Settings --> ActiveX "not secure for Scripting" is deactivated, Unknown ActiveX Elements is disabled as well.
