### ISSUE TITLE
Building on Kali via go get or via source generates exception

### ISSUE THREAD

**Issue by johnnyDEP** [sensepost/ruler#63]
Just following setup guide on up-to-date Kali build. Getting the following:

# command-line-arguments
./ruler.go:89: config.Proxy undefined (type utils.Session has no field or method Proxy)
./ruler.go:155: undefined: autodiscover.Init
./ruler.go:160: not enough arguments in call to autodiscover.BruteForce
./ruler.go:162: not enough arguments in call to autodiscover.UserPassBruteForce
./ruler.go:303: config.Proxy undefined (type utils.Session has no field or method Proxy)
./ruler.go:520: undefined: mapi.FetchRules
./ruler.go:786: undefined: mapi.WebViewPersistenceObjectStream
./ruler.go:793: undefined: mapi.PidTagFolderWebViewInfo

Its very likely that I have setup my Go env incorrectly, but I can query the Go version and still run the old version of ruler just fine. I was just looking to build the latest code from github. Appreciate an help you might lend. If "It works on my machine", then feel free to close 👍

**Comment by staaldraad** [comment]
Hi!

I have the feeling that the Go env from Kali is different from the one that you have setup. It looks like it is trying to build the new version of ruler against some old code.

This happens because the ruler imports look as follows:
```
github.com/sensepost/ruler/autodiscover
github.com/sensepost/ruler/mapi
```

When Go does the compilation, it will search for those paths in `$GOPATH/src` and I'm guessing that `$GOPATH/src` contains the old version of ruler. What you could do is try and find where Kali is storing the ruler libraries: `find / -name autodiscover.go` and then overwrite that path with the version you get from `git clone`.

The releases do track latest code, so [Bleeding edge](https://github.com/sensepost/ruler/releases/tag/2.2.0) is built off of master. But I understand the desire to build from source, I do the same :)

If I find some time I'll spin up a Kali image and see if I can track down where Ruler is located

**Comment by johnnyDEP** [comment]
Thanks for the reply, I was able to build it just fine on a new Kali VM. I think your answer is correct I must have fubar'd it by mixing environments.

**Comment by staaldraad** [comment]
Awesome, happy to hear that!
