### ISSUE TITLE
When will the rule sync to outlook?

### ISSUE THREAD

**Issue by qiyidefeng** [sensepost/ruler#81]
I connected to my test exchange server using pop3 and the rule was successfully added to server, but the rule was not sync to outlook client after a long time. 
When does the rule sync to outlook? Shall I connect to the server using Exchange mode?

**Comment by staaldraad** [comment]
Hi @qiyidefeng 

Rules, forms and other Outlook attributes are not synced through pop3. These are Exchange/Outlook specific attributes and are not covered by the pop3 protocol. Ruler makes use of MAPI/HTTP or MAPI/RPC to sync these settings to the Exchange server. The Outlook client needs to use either MAPI/HTTP or MAPI/RPC  (I guess this can be called Exchange mode) in order to sync with Exchange and apply the rules.

**Comment by qiyidefeng** [comment]
@staaldraad thanks
