### ISSUE TITLE
Feature Request: Connect directly to EWS without Autodiscover

### ISSUE THREAD

**Issue by mlinton** [sensepost/ruler#95]
I have found a few instances where the autodiscover service resolves to an o365 service, but the company still has enabled access to the legacy on-prem ews services.  The autodiscover service fails to find the end-point, but the EWS service is still available.

Would it be possible to add an option to manually specific the EWS endpoint as a parameter.

Cheers.

**Comment by staaldraad** [comment]
Hi, thanks for the request

Two things, 
1) Ruler doesn't use EWS, everything is done through MAPI - either the MAPI/HTTP endpoint or the RPC/HTTP endpoint. 
2) These endpoints can be set and autodiscover will be bypassed. To do this you use the `--config` option: [https://github.com/sensepost/ruler/wiki/Getting-Started#the-config-file](https://github.com/sensepost/ruler/wiki/Getting-Started#the-config-file). It does require you to know bits of information about the user that are usually obtained through Autodiscover.

If you are looking for EWS access you could try [NtlmRelayToEWS](https://github.com/Arno0x/NtlmRelayToEWS). It doesn't do the full range of attacks Ruler offers, since EWS can't set those values (forms, client-side rules) but you can atleast do something like the "Homepage" attack.

**Comment by void-in** [comment]
Also, the Metasploit module https://www.rapid7.com/db/modules/auxiliary/scanner/http/owa_ews_login can be used for ews brute force.
